### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology#22]
![image](https://user-images.githubusercontent.com/3974108/104829100-61fb2e00-583e-11eb-86e1-6696c7bb1301.png)

I'm wondering if we should rename the project to “地震学参考书”.

**Comment by core-man** [comment]
Yes to me.

**Comment by seisman** [comment]
Feel free to work on it if you have time.

**Comment by core-man** [comment]
Okay.

**Comment by core-man** [comment]
地震“学”参考书 or 地震学参考书？

**Comment by seisman** [comment]
地震“学”参考书. A reference book by seismo-learn, not a seismology reference book.

**Comment by seisman** [comment]
Reopen the issue so that we won't forget to update the main site and other projects.
